
/**************************************************************
 *	
 *	gameSong, 8 bit, 11025Hz,
 *	1 channel, 370646 bytes/channel
 *	Total Size: 1 * 370646 + 4 (header) = 370690 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Courtney Rogers\OneDrive\Documents\CS2261 - Spring\Milestones\M01_CourtneyRogers\gameSong.wav
 *	Time-stamp: Tue Apr 04 19:21:21 2017
 *	
 **************************************************************/

#ifndef __GAMESONGH__
#define __GAMESONGH__

#define GAMESONGFREQ 11025
#define GAMESONGLEN 370646

extern const unsigned char gameSong[370646];

#endif /* __GAMESONGH__ */
