
/**************************************************************
 *	
 *	gasp, 8 bit, 11025Hz,
 *	1 channel, 11520 bytes/channel
 *	Total Size: 1 * 11520 + 4 (header) = 11564 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Courtney Rogers\OneDrive\Documents\CS2261 - Spring\Milestones\M01_CourtneyRogers\Music\gasp.wav
 *	Time-stamp: Mon Apr 24 22:13:22 2017
 *	
 **************************************************************/

#ifndef __GASPH__
#define __GASPH__

#define GASPFREQ 11025
#define GASPLEN 11520

extern const unsigned char gasp[11520];

#endif /* __GASPH__ */
