
/**************************************************************
 *	
 *	instructionsSong, 8 bit, 11025Hz,
 *	1 channel, 171599 bytes/channel
 *	Total Size: 1 * 171599 + 4 (header) = 171643 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Courtney Rogers\OneDrive\Documents\CS2261 - Spring\Milestones\M01_CourtneyRogers\instructionsSong.wav
 *	Time-stamp: Tue Apr 04 19:21:15 2017
 *	
 **************************************************************/

#ifndef __INSTRUCTIONSSONGH__
#define __INSTRUCTIONSSONGH__

#define INSTRUCTIONSSONGFREQ 11025
#define INSTRUCTIONSSONGLEN 171599

extern const unsigned char instructionsSong[171599];

#endif /* __INSTRUCTIONSSONGH__ */
