
/**************************************************************
 *	
 *	loseSong, 8 bit, 11025Hz,
 *	1 channel, 956250 bytes/channel
 *	Total Size: 1 * 956250 + 4 (header) = 956294 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Courtney Rogers\OneDrive\Documents\CS2261 - Spring\Milestones\M01_CourtneyRogers\loseSong.wav
 *	Time-stamp: Tue Apr 04 19:21:09 2017
 *	
 **************************************************************/

#ifndef __LOSESONGH__
#define __LOSESONGH__

#define LOSESONGFREQ 11025
#define LOSESONGLEN 956250

extern const unsigned char loseSong[956250];

#endif /* __LOSESONGH__ */
